const DEFAULT_MESSAGES = {
    LOGIN_ERROR: 'Se ha producido un error al autenticar el usuario'
}

const CONSTANTES = {
    GENERIC:{
        OPEN_DIALOG: 'OPEN_DIALOG',
        CLOSE_DIALOG: 'CLOSE_DIALOG',
    },
    LOGIN: {
        LOGIN_SUCCESS:'LOGIN_SUCCESS',
        LOGIN_ERROR:'LOGIN_ERROR',
        LOGOUT: 'LOGOUT'
    },
    USUARIOS:{
        GET_USUARIOS:'GET_USUARIOS',
        GET_USUARIOS_SUCCESS:'GET_USUARIOS_SUCCESS',
        OPEN_CREAR_USUARIO_MODAL: 'OPEN_CREAR_USUARIO_MODAL',
        CLOSE_CREAR_USUARIO_MODAL: 'CLOSE_CREAR_USUARIO_MODAL',
    },
    DEFAULT_MESSAGES
}



export default CONSTANTES;